### ISSUE TITLE
BackgroundMusic App is not opening after install

### ISSUE THREAD

**Issue by varunvraja** [kyleneideck/BackgroundMusic#723]
I have a Macbook Pro 14" M3. I cannot get the BackgroundMusic App to run after being installed. I have uninstalled it and reinstalled it using homebrew and then tried using the installer. I tried resart my device multiple times and tried investigating the issue. No solution was found. Still, I cannot get any interface of BackgroundMusic to show like in this video: https://www.youtube.com/watch?v=YaBmH758RaA. It seems like background music is running in the background, but no interface controls are showing.

**What am I doing wrong?**

**Comment by tfg1434** [comment]
I have the same issue

**Comment by louisdauvois** [comment]
I have the same issue

**Comment by tempestbaum** [comment]
I am also having this issue. This is the only thing that shows up for me when I launch Background Music:

<img width="312" alt="Screenshot 2024-03-08 at 01 39 17" src="https://github.com/kyleneideck/BackgroundMusic/assets/162673095/a0c4a7a7-6b54-4ea7-849f-65dc6959fb52">

I am on a MacBook Pro 14" with an M3 chip running MacOS Sonoma.

**Comment by cespuglioexe** [comment]
I have the same issue on M1 MacAir (MacOS 14.0). After restarting, the UI briefly appears in the menu bar but then disappears.

**Comment by blockerbee** [comment]
Adding onto the thread that I am having the same problem. M1 Macbook Pro on Sonoma 14.2.1 .
Background Music is running and I am able to use it as a source for input, but I can't access the application interface, the icon isn't showing up in the toolbar. Like cespuglioexe, the icon/UI only shows up for a short amount of time after restarting my laptop and then disappears. 

<img width="1508" alt="Screenshot 2024-03-21 at 9 51 24 PM" src="https://github.com/kyleneideck/BackgroundMusic/assets/7545021/9a287840-e28b-4915-8907-26a5c0cd34f5">

**Comment by josephyooo** [comment]
Same deal on M3 MacBook Air on Sonoma 14.3

**Comment by ickc** [comment]
Were you running programs that intercept audio such as Rewind? Quitting that would make BackgroundMusic works again.

**Comment by cespuglioexe** [comment]
I think the issue might have been fixed with v0.4.3. I tried installing it today (via Homebrew) and it works as intended
<img width="359" alt="Screenshot 2024-05-22 at 11 09 39" src="https://github.com/kyleneideck/BackgroundMusic/assets/80582199/da05d9c7-1569-44e6-b7e9-6907de5cd12a">

**Comment by molotovich** [comment]
I tried installing it today from the PKG, issue persists, i uninstalled using the bash script.

**Comment by ExpertzZ** [comment]
issue persists

**Comment by zhkvivan** [comment]
same issue on m4 mac pro sequoia 15.5
